### ISSUE TITLE
macOS CLI新建项目出错

### ISSUE THREAD

**Issue by scfido** [WangJunZzz/abp-vnext-pro#115]
环境macOS

执行命令：
```
lion.abp new -t pro -c Letu -p Cms 
```

> [14:58:58 INF] ABP Pro CLI (https://https://doc.cncore.club/)
[14:58:58 INF] 请输入 lion.abp help 查看所有命令
[14:58:59 INF] Lion AbpPro Version:8.0.0.1
[14:58:59 INF] 模板生成中......
[14:59:02 INF] OutputFolder:/Users/fuyun/sources/abp-samples/abppro/Letu.Cms
[14:59:03 ERR] An error occurred trying to start process 'explorer.exe' with working directory '/Users/fuyun/sources/abp-samples/abppro'. No such file or directory
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'explorer.exe' with working directory '/Users/fuyun/sources/abp-samples/abppro'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Lion.AbpPro.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/Commands/NewCommand.cs:line 112
   at Lion.AbpPro.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/CliService.cs:line 43
   at Lion.AbpPro.Cli.CliService.RunAsync(String[] args) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/CliService.cs:line 28

**Comment by WangJunZzz** [comment]
暂时不支持mac os
