### ISSUE TITLE
macOS使用lion.abp 新建项目报错，

### ISSUE THREAD

**Issue by ClementJob** [WangJunZzz/abp-vnext-pro#123]
[14:22:29 INF] ABP Pro CLI (https://https://doc.cncore.club/)
[14:22:29 INF] 请输入 lion.abp help 查看所有命令
[14:22:30 INF] Lion AbpPro Version:8.0.2.1
[14:22:30 INF] 模板生成中......
[14:22:31 INF] OutputFolder:/Users/jobclement/Projects/codeup/YunYi.Recycle
[14:22:31 ERR] An error occurred trying to start process 'explorer.exe' with working directory '/Users/jobclement/Projects/codeup'. No such file or directory
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'explorer.exe' with working directory '/Users/jobclement/Projects/codeup'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Lion.AbpPro.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/Commands/NewCommand.cs:line 112
   at Lion.AbpPro.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/CliService.cs:line 43
   at Lion.AbpPro.Cli.CliService.RunAsync(String[] args) in /home/runner/work/abp-vnext-pro/abp-vnext-pro/aspnet-core/frameworks/src/Lion.AbpPro.Cli.Core/Lion/AbpPro/Cli/CliService.cs:line 28

**Comment by WangJunZzz** [comment]
cli 暂时只支持windows
