### ISSUE TITLE
数据迁移报错！ 使用的是Mysql?   我试过几次想改成SqlServer， 都不成功。

### ISSUE THREAD

**Issue by luzwales** [WangJunZzz/abp-vnext-pro#134]
PS C:\Users\Andre\Desktop\Flex.BookStore\aspnet-core\src\Flex.BookStore.EntityFrameworkCore> dotnet ef migrations add init1
Build started...
Build succeeded.
Done. To undo this action, use 'ef migrations remove'
PS C:\Users\Andre\Desktop\Flex.BookStore\aspnet-core\src\Flex.BookStore.EntityFrameworkCore> dotnet ef database update
Build started...
Build succeeded.
Applying migration '20241117064706_init1'.
Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX `IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_Execution~` ON `AbpAuditLogActions` (`TenantId`, `ServiceName`, `MethodName`, `ExecutionTime`);
MySqlConnector.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483

**Comment by luzwales** [comment]
改成 sqlserver出现这个， [22:18:28 INF] Request starting HTTP/1.1 GET http://localhost:44315/ - null null
[22:18:29 ERR] Failed executing DbCommand (93ms) [Parameters=[@__isEnabled_0='?' (DbType = Boolean)], CommandType='Text', CommandTimeout='30']
SELECT [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[CreatorId], [a].[CultureName], [a].[DeleterId], [a].[DeletionTime], [a].[DisplayName], [a].[ExtraProperties], [a].[FlagIcon], [a].[IsDefault], [a].[IsDeleted], [a].[IsEnabled], [a].[LastModificationTime], [a].[LastModifierId], [a].[TenantId], [a].[UiCultureName]
FROM [AbpLanguages] AS [a]
WHERE [a].[IsDeleted] = CAST(0 AS bit) AND [a].[TenantId] IS NULL AND [a].[IsEnabled] = @__isEnabled_0
[22:18:29 ERR] An exception occurred while iterating over the results of a query for context type 'Lion.AbpPro.LanguageManagement.EntityFrameworkCore.LanguageManagementDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'AbpLanguages'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:3c72e64e-7c9b-4848-97ac-a365107d0b20
Error Number:208,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'AbpLanguages'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
?

**Comment by WangJunZzz** [comment]
看一下这个：https://github.com/WangJunZzz/abp-vnext-pro/issues/35

**Comment by luzwales** [comment]
@WangJunZzz   我用MySql也报错， 
Applying migration '20241125142042_init01'.
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX `IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_Execution~` ON `AbpAuditLogActions` (`TenantId`, `ServiceName`, `MethodName`, `ExecutionTime`);
MySqlConnector.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 108
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Specified key was too long; max key length is 1000 bytes

![image](https://github.com/user-attachments/assets/12480b47-c024-4f3a-b8cf-28f8b4551d82)
