### ISSUE TITLE
前端接口指向Gateway，我需要修改一下前端代码中的请求地址才可以只请求Host吗

### ISSUE THREAD

**Issue by OldKing-lion** [WangJunZzz/abp-vnext-pro#29]
启动项目，登录不了，f12查看请求地址是gateway的地址，如果我只想用host，需要修改前端调用接口地址吗，文档中的说明不太完善

![image](https://user-images.githubusercontent.com/13028615/153538538-afcc6d17-fadd-4f3a-b8ef-f975e509735b.png)

**Comment by OldKing-lion** [comment]
按文档中的这几个步骤启动起来，就要经过网关，还没研究过console,如果配置里console改为true，那host地址是不是也要调整呢

**Comment by WangJunZzz** [comment]
如果不需要网关，直接修改前端地址为apihost的地址即可

**Comment by OldKing-lion** [comment]
好的，谢谢

**Comment by OldKing-lion** [comment]
那我问一下，如果需要网关怎么配置，我学习一下，目前我gateway Host 和ids都启动了，gateway consul配置:
![image](https://user-images.githubusercontent.com/13028615/153539673-e9aa23a9-d608-421e-b697-1061f9c5421f.png)
host配置：
![image](https://user-images.githubusercontent.com/13028615/153539695-2b790f1a-4f46-4cd0-956c-dbc860d5c0fb.png)

登录请求会提示502badgateway

**Comment by WangJunZzz** [comment]
Consul安装好之后，apihost项目的配置文件 consul.enabled=true,启动的时候修该环境变量为Consul。

**Comment by OldKing-lion** [comment]
懂了，多谢指点

**Comment by OldKing-lion** [comment]
1、consul agent -dev
![image](https://user-images.githubusercontent.com/13028615/153544065-03e71be8-56d1-4143-9631-c4913676978e.png)
2、修改Host consul配置：
![image](https://user-images.githubusercontent.com/13028615/153544111-c6ca7c9c-a426-430f-bd67-004f2c51d090.png)
3、Consul控制台输出检测到host的服务了：
![image](https://user-images.githubusercontent.com/13028615/153544161-213d8a17-f3d2-4a95-b4a3-a530d0b3431e.png)

4、Gateway那边的配置需要调整什么吗，现在登录仍是502...

**Comment by WangJunZzz** [comment]
登录地址改为网关地址没有

**Comment by WangJunZzz** [comment]
apihost配置 
  "Consul": {
    "Enabled": true,
    "Host": "http://localhost:8500",
    "Service": "Project-Service"
  },

**Comment by OldKing-lion** [comment]
登录地址是网关地址  consul端口也是8500了，控制台显示的错误信息
 Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMFD4ETKKJSF:00000003, previousRequestId: no previous request id, message: Error Code: RequestTimedOutError Message: Timeout making http request, exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 90 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
       ---> System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/gateway/api/app/account/login, request method: POST

**Comment by OldKing-lion** [comment]
登录请求：![image](https://user-images.githubusercontent.com/13028615/153544617-7c84895e-36c8-449b-8055-98b509356d93.png)
host配置：![image](https://user-images.githubusercontent.com/13028615/153544662-a4aefeea-c170-4edf-b237-982490f56b08.png)
gateway consul配置： ![image](https://user-images.githubusercontent.com/13028615/153544707-3fa6fc4f-511d-4f80-9bd6-cb54f7cf0eb5.png)

**Comment by OldKing-lion** [comment]
可以了，gateway那边不用改。谢谢。。
