### ISSUE TITLE
Vue前端启动失败问题

### ISSUE THREAD

**Issue by litiansky** [WangJunZzz/abp-vnext-pro#53]
前端启动时候会提示很多下面这样的错误，我看ant的引用有的是用了按需加载吗？但没看到有相关的组件啊，求大神明示
>  Failed to resolve import "C:/Users/xxx/Downloads/abp-vnext-pro-49ec9009e8248b7931e0c4c9c2f29427932a4bc2/vben28/node_modules/_ant-design-vue@3.2.10@/ant-design-vue/es/modal/style/index" from "src\router\guard\index.ts". Does the file exist?

**Comment by WangJunZzz** [comment]
检查node版本- 大于16
安装pnpm 
执行 pnpm install

**Comment by litiansky** [comment]
我的node版本是16.16.0，使用pnpm安装后可以运行了，但是访问项目地址后报这个错误，不能跳转登录页：
`
Uncaught (in promise) TypeError: Cannot destructure property 'currentRoute' of 'useRouter(...)' as it is undefined.
    at useTitle (useTitle.ts:16:11)
    at setup (App.vue:20:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at render (runtime-core.esm-bundler.js:6209:13)
    at mount (runtime-core.esm-bundler.js:4402:25)
`

我用的是abp官网下载的全新后台，没使用我们这个服务端，但我觉得不会是这个原因吧？

**Comment by litiansky** [comment]
抱歉抱歉，已经好了，后面的问题是因为我之前改动了源码，感谢帮忙解答。
